# @name token
POST  http://0.0.0.0:8080/auth HTTP/1.1
Content-Type: application/json

{
  "userId": "2c0902c8-2314-41a1-8351-5f74eb473f96",
  "password": "pass1"
}
###

# @name newTodo
POST  http://0.0.0.0:8080/todos/add HTTP/1.1
Authorization: Bearer {{token.response.body.token}}
Content-Type: application/json

{
  "title": "New todo"
}
###

GET  http://0.0.0.0:8080/todos/find/{{newTodo.response.body.newUuid}}
###

GET  http://0.0.0.0:8080/todos/list/all
###






